from task.views.common_task_interface_view import CommonTaskInterfaceView
from task.views.common_task_interface_view import MathSolutionsView
from task.views.common_task_interface_view import render_task
