# Generated by Django 4.2.6 on 2024-02-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
