# Generated by Django 4.2.6 on 2024-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_alter_sourcemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='descriptions',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
