# Generated by Django 4.2.6 on 2024-04-01 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0003_alter_categorymodel_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionmodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='notionmodel',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notion.categorymodel'),
        ),
        migrations.AlterField(
            model_name='notionmodel',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notion.sourcemodel'),
        ),
    ]
