# Generated by Django 4.2.14 on 2025-02-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointTransaction',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='UserPoint',
            new_name='UserAccount',
        ),
        migrations.RemoveField(
            model_name='points',
            name='mentorship',
        ),
        migrations.RemoveField(
            model_name='points',
            name='task',
        ),
        migrations.RemoveField(
            model_name='points',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='users_trans_timesta_a8585c_idx',
            old_name='users_point_timesta_69bcd2_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='users_trans_transac_dd58bb_idx',
            old_name='users_point_transac_470df7_idx',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
