# Generated by Django 4.2.14 on 2025-01-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorship',
            options={'verbose_name': 'Менторство', 'verbose_name_plural': 'Менторство'},
        ),
        migrations.AlterModelOptions(
            name='mentorshiprequest',
            options={'verbose_name': 'Запрос на менторство', 'verbose_name_plural': 'Запросы на менторство'},
        ),
        migrations.AlterModelOptions(
            name='userapp',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
