# Generated by Django 4.2.14 on 2025-02-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Очки за выполненные задания', 'verbose_name_plural': 'Очки за выполненные задания'},
        ),
        migrations.AlterField(
            model_name='points',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
