# Generated by Django 4.2.14 on 2025-02-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pointtransaction_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Транзакция вознаграждения', 'verbose_name_plural': 'Транзакция вознаграждений'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Вознаграждения пользователя', 'verbose_name_plural': 'Вознаграждения пользователей'},
        ),
    ]
