# Generated by Django 4.2.14 on 2024-08-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mentorshiprequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorshiprequest',
            unique_together=set(),
        ),
    ]
