services:

  app-wse:
    container_name: app-wse
    image: app-wse
    volumes:
      - ./app-wse:/app-wse
      - ./static:/app-wse/static
    build:
      context: ./app-wse
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./app-wse/.env
    command:
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db-postgres-wse

  db-postgres-wse:
    container_name: db-postgres-wse
    image: db-postgres-wse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    build:
      context: ./app-wse
      dockerfile: Dockerfile.postgres
    env_file:
      - ./app-wse/.env.postgres

  server-wse:
    container_name: server-wse
    image: server-wse
    build:
      context: ./nginx
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app-wse

volumes:
  postgres_data:
  static:
