services:

  wse-project:
    container_name: wse-project-dev
    image: wse-project-dev
    volumes:
      - .:/wselfedu
      - static_volume:/wselfedu/static
    build:
      context: .
      dockerfile: ./docker/project/Dockerfile.dev
    expose:
      - 8000
    env_file:
      - .env_vars/.env
    command:
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - wse-db-postgres
      - wse-redis

  wse-db-postgres:
    container_name: wse-db-postgres
    image: wse-db-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - .env_vars/.env.postgres
    ports:
      - 6543:5432

  wse-server:
    container_name: wse-server
    image: wse-server
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - static_volume:/wselfedu/static
    ports:
      - 80:80
    depends_on:
      - wse-project

  wse-redis:
    container_name: wse-redis
    image: wse-redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    hostname: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
  static_volume:
