# Configuring Ruff
# https://docs.astral.sh/ruff/configuration/

exclude = [
    ".github/*",
    ".idea/*",
    ".venv/*",
    "docker/*",
    "postgres_data/*",
    "templates/*",
    ".env*",
    "*/migrations/*",
]
line-length = 79

[lint]
preview = true  # checks will include unstable rules and fixes
select = [
    "B",   # flake8-bugbear
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "W",   # pycodestyle
]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"

[format]
quote-style = "single"
