# =============================================================================
# HELP
# =============================================================================

.PHONY: help

help:  ## Show all available commands
	@echo "==================="
	@echo "Available commands:"
	@echo "==================="
	@echo ""
	@echo "  Code Quality"
	@echo "  -------------------"
	@echo "  type-check    - Check types with mypy"
	@echo "  test          - Run tests"
	@echo "  lint          - Check code style (read-only)"
	@echo "  fix           - Auto-fix lint issues"
	@echo "  check         - Full check (format + fix + type-check + test)"
	@echo "  ci            - CI check (read-only: lint + type-check + test)"
	@echo "  format        - Format code with ruff"
	@echo ""
	@echo "  Setup"
	@echo "  -------------------"
	@echo "  setup         - Install dependencies"
	@echo ""
	@echo "  Docker"
	@echo "  -------------------"
	@echo "  run           - Run docker compose with build"
	@echo "  rebuild       - Rebuild docker compose with clean"
	@echo ""
	@echo "  Utils"
	@echo "  -------------------"
	@echo "  clean         - Remove cache files"
	@echo ""
	@echo "  Documentation"
	@echo "  -------------------"
	@echo "  Build and run via Python virtual environment:"
	@echo "  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	@echo "  docs-build    - Build HTML documentation"
	@echo "  docs-open     - Build docs and open in browser"
	@echo ""
	@echo "  Build and run via Docker:"
	@echo "  ~~~~~~~~~~~~~~~~~~~~~~~~"
	@echo "  docs-build    - Build documentation Docker image"
	@echo "  docs-run      - Build and run documentation Docker container"
	@echo "  docs-stop     - Stop documentation Docker container"
	@echo "  docs-clean    - Remove documentation Docker image and container"