# syntax=docker/dockerfile:1.7-labs

FROM python:3.12-bookworm

WORKDIR /wselfedu
COPY pyproject.toml ./

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
COPY requirements.dev.txt /tmp/requirements.dev.txt
RUN pip install -r /tmp/requirements.dev.txt

COPY . .
