FROM python:3.12-bookworm

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /wselfedu

RUN mkdir -p /wselfedu/static

RUN adduser --disabled-password app-user
RUN chown -R app-user /wselfedu/static
USER app-user

COPY . .
