# syntax=docker/dockerfile:1.7-labs

FROM python:3.12-bookworm

WORKDIR /wselfedu

RUN pip install --upgrade pip && \
    pip install playwright && \
    pip install pytest-playwright==0.5.0 && \
    playwright install && \
    playwright install-deps

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY requirements.dev.txt requirements.dev.txt
RUN pip install -r requirements.dev.txt

RUN adduser --disabled-password app-user
USER app-user

COPY . .
