# Generated by Django 6.1 on 2026-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Перевод слова на английский',
                'verbose_name_plural': 'Переводы слов на английский',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на английском')),
            ],
            options={
                'verbose_name': 'Английское слово',
                'verbose_name_plural': 'Английские слова',
            },
        ),
        migrations.CreateModel(
            name='NativeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на родном языке')),
            ],
            options={
                'verbose_name': 'Слово на родном языке',
                'verbose_name_plural': 'Слова на родном языке',
            },
        ),
    ]
