# Generated by Django 6.1 on 2026-09-10 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foreign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtranslation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='englishtranslation',
            name='foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.englishword', verbose_name='Слово на английском'),
        ),
        migrations.AddField(
            model_name='nativeword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='englishtranslation',
            name='native',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.nativeword', verbose_name='Слово на родном языке'),
        ),
        migrations.AlterUniqueTogether(
            name='englishword',
            unique_together={('user', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='nativeword',
            unique_together={('user', 'word')},
        ),
    ]
