# Generated by Django 5.2.5 on 2025-08-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exercise name', max_length=100, verbose_name='Наименование упражнение')),
                ('object_id', models.PositiveBigIntegerField(help_text='Primary key exercise name field in exercise model')),
                ('content_type', models.ForeignKey(help_text='Exercise model in ContentType', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('discipline', models.ForeignKey(help_text='Discipline', on_delete=django.db.models.deletion.CASCADE, to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_exerci_content_9b7acd_idx')],
            },
        ),
    ]
