# Generated by Django 5.2.7 on 2025-11-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
    ]
