# Generated by Django 5.2.7 on 2025-12-07 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='task_io',
            field=models.ForeignKey(help_text='Task I/O: text, number, test, ...', on_delete=django.db.models.deletion.CASCADE, to='core.taskio', verbose_name='Тип ввода/вывода'),
        ),
    ]
