# Generated by Django 5.2.5 on 2025-08-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(1, 'Активировано'), (0, 'Деактивировано')], default=0, verbose_name='Статус активации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Статус активации упражнения',
                'verbose_name_plural': 'Статусы активации упражнения',
                'db_table': 'study_exercise_active',
            },
        ),
        migrations.CreateModel(
            name='ExerciseExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Ежедневное задание')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Срок выполнения упражнения',
                'verbose_name_plural': 'Сроки выполнения упражнения',
                'db_table': 'study_exercise_expiration',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTaskAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Вознаграждение за задание',
                'verbose_name_plural': 'Вознаграждения за задание',
                'db_table': 'study_exercise_task_award',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTaskCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Количество назначенных заданий',
                'verbose_name_plural': 'Количества назначенных заданий',
                'db_table': 'study_exercise_task_count',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercise', to='core.exercise', verbose_name='Назначенное упражнение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'study_exercise_assigned',
            },
        ),
    ]
