# Generated by Django 6.0.1 on 2026-03-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(choices=[(1, 'Activated'), (0, 'Deactivated')], default=0, verbose_name='Activate status')),
            ],
            options={
                'verbose_name': 'Active exercise status',
                'verbose_name_plural': 'Active exercise statuses',
                'db_table': 'study_assigned_active',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exercise_object_id', models.PositiveIntegerField()),
                ('required_count', models.PositiveSmallIntegerField(verbose_name='Кол-во заданий')),
                ('period_type', models.CharField(choices=[('Ежедневно', 'Daily'), ('По назначено наставником', 'Appointment')], max_length=30, verbose_name='Периодичность выполнения')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Временная метка назначения упражнения')),
                ('is_active', models.BooleanField(default=False, verbose_name='Актировано ли для выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено ли упражнение полностью')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Временная метка назначения упражнения')),
            ],
            options={
                'verbose_name': 'Доступность упражнения',
                'verbose_name_plural': 'Доступность упражнений',
                'db_table': 'study_exercise_availability',
            },
        ),
        migrations.CreateModel(
            name='ExerciseExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Is daily exercise')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration date')),
            ],
            options={
                'verbose_name': 'Exercise completion expiration',
                'verbose_name_plural': 'Exercise completion expirations',
                'db_table': 'study_assigned_expiration',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exercise_object_id', models.PositiveIntegerField()),
                ('success_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество успешных выполнения')),
                ('failure_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество неуспешных выполнений')),
                ('tracking_date', models.DateField(auto_now=True, verbose_name='Дата для отслеживание ежедневных упражнений')),
            ],
            options={
                'verbose_name': 'Лог выполнения упражнений',
                'verbose_name_plural': 'Логи выполнения упражнений',
                'db_table': 'study_exercise_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exercise_object_id', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('За каждое задание', 'Per Case'), ('За завершение всех заданий', 'Complete')], max_length=30, verbose_name='Тип вознаграждения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вознаграждение')),
            ],
            options={
                'verbose_name': 'Вознаграждение за упражнение',
                'verbose_name_plural': 'Вознаграждения за упражнения',
                'db_table': 'study_exercise_reward',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTaskCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('count', models.PositiveSmallIntegerField(verbose_name="Assigned exercise's task count")),
            ],
            options={
                'verbose_name': "Assigned exercise's task count",
                'verbose_name_plural': "Assigned exercise's task count",
                'db_table': 'study_assigned_task_count',
            },
        ),
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Progress change scale name', max_length=30)),
                ('study', models.PositiveSmallIntegerField(default=7, help_text='\n        Significance for the transition between the "Study-Repeat" stages\n        ', verbose_name='Study')),
                ('repeat', models.PositiveSmallIntegerField(default=10, help_text='\n        Significance for the transition between the "Repeat-Examine" stages\n        ', verbose_name='Repeat')),
                ('examine', models.PositiveSmallIntegerField(default=16, help_text='\n        Significance for the transition between the "Examine-Know" stages\n        ', verbose_name='Examine')),
                ('know', models.PositiveSmallIntegerField(default=17, help_text='Maximum progress value', verbose_name='Know')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Progress of study',
                'verbose_name_plural': 'Progress in learning',
                'db_table': 'study_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercise', to='core.exercise', verbose_name='Assigned exercise')),
            ],
            options={
                'verbose_name': 'Assigned exercise',
                'verbose_name_plural': 'Assigned exercises',
                'db_table': 'study_assigned',
            },
        ),
    ]
