# Generated by Django 6.0 on 2026-01-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationCompletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveSmallIntegerField(verbose_name='Кол-во попыток')),
                ('success_count', models.PositiveSmallIntegerField(verbose_name='Кол-во успешных решений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Выполнение назначенного задания',
                'verbose_name_plural': 'Выполнения назначенного задания',
                'db_table': 'study_assigned_completion',
            },
        ),
        migrations.CreateModel(
            name='ExerciseActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(1, 'Активировано'), (0, 'Деактивировано')], default=0, verbose_name='Статус активации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Статус активации упражнения',
                'verbose_name_plural': 'Статусы активации упражнения',
                'db_table': 'study_assigned_active',
            },
        ),
        migrations.CreateModel(
            name='ExerciseExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Ежедневное задание')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Срок выполнения упражнения',
                'verbose_name_plural': 'Сроки выполнения упражнения',
                'db_table': 'study_assigned_expiration',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTaskAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.PositiveSmallIntegerField(verbose_name='Вознаграждение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Вознаграждение за задание',
                'verbose_name_plural': 'Вознаграждения за задание',
                'db_table': 'study_assigned_task_award',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTaskCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Количество назначенных заданий',
                'verbose_name_plural': 'Количества назначенных заданий',
                'db_table': 'study_assigned_task_count',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование версии шкалы прогресса', max_length=30)),
                ('study', models.PositiveSmallIntegerField(default=7, help_text='Значение для смены стадий "Изучаю-Повторяю"', verbose_name='Изучаю')),
                ('repeat', models.PositiveSmallIntegerField(default=10, help_text='Значение для смены стадии "Повторяю-Проверяю"', verbose_name='Повторяю')),
                ('examine', models.PositiveSmallIntegerField(default=16, help_text='Значение для смены стадии "Проверяю-Знаю"', verbose_name='Проверяю')),
                ('know', models.PositiveSmallIntegerField(default=17, help_text='Максимальное значение прогресса', verbose_name='Знаю')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Прогресс изучения',
                'verbose_name_plural': 'Прогрессы изучения',
                'db_table': 'study_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercise', to='core.exercise', verbose_name='Назначенное упражнение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'study_assigned',
            },
        ),
    ]
