# Generated by Django 5.2.7 on 2025-12-07 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseassigned',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.mentorship', verbose_name='Наставничество'),
        ),
        migrations.AddField(
            model_name='exerciseactive',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_status', to='study.exerciseassigned', verbose_name='Назначенное упражнение'),
        ),
        migrations.AddField(
            model_name='assignationcompletes',
            name='assignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completion', to='study.exerciseassigned', verbose_name='Назначенное упражнение'),
        ),
        migrations.AddField(
            model_name='exerciseexpiration',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_expiration', to='study.exerciseassigned', verbose_name='Назначенное упражнение'),
        ),
        migrations.AddField(
            model_name='exercisetaskaward',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_award', to='study.exerciseassigned', verbose_name='Упражнение'),
        ),
        migrations.AddField(
            model_name='exercisetaskcount',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_task_count', to='study.exerciseassigned', verbose_name='Количество назначенных заданий'),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='exerciseassigned',
            index=models.Index(fields=['mentorship', 'exercise'], name='study_assig_mentors_c54545_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user'], name='study_progr_user_id_16d82f_idx'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(condition=models.Q(('study__lt', models.F('repeat')), ('repeat__lt', models.F('examine')), ('examine__lt', models.F('know'))), name='progress_study_lt_repeat_lt_examine_lt_know'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_progress_name'),
        ),
    ]
