# Generated by Django 5.2.5 on 2025-08-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseassigned',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.mentorship', verbose_name='Наставничество'),
        ),
        migrations.AddField(
            model_name='exerciseactive',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_status', to='study.exerciseassigned', verbose_name='Назначенное упражнение'),
        ),
        migrations.AddField(
            model_name='exerciseexpiration',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_expiration', to='study.exerciseassigned', verbose_name='Назначенное упражнение'),
        ),
        migrations.AddField(
            model_name='exercisetaskaward',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_award', to='study.exerciseassigned', verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='exercisetaskcount',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_task_count', to='study.exerciseassigned', verbose_name='Количество назначенных заданий'),
        ),
        migrations.AddIndex(
            model_name='exerciseassigned',
            index=models.Index(fields=['mentorship', 'exercise'], name='study_exerc_mentors_619357_idx'),
        ),
    ]
