# Generated by Django 6.0.1 on 2026-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='failure_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество неуспешных выполнений'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='success_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество успешных выполнения'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='tracking_date',
            field=models.DateField(auto_now=True, verbose_name='Дата для отслеживание ежедневных упражнений'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Вознаграждение'),
        ),
    ]
