# Generated by Django 6.0.1 on 2026-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseavailability',
            options={'verbose_name': 'Exercise availability', 'verbose_name_plural': 'Exercise availabilities'},
        ),
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exercise performance log', 'verbose_name_plural': 'Exercise performance logs'},
        ),
        migrations.AlterModelOptions(
            name='exercisereward',
            options={'verbose_name': 'Exercise reward', 'verbose_name_plural': 'Exercise rewards'},
        ),
        migrations.AlterField(
            model_name='exerciseactive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exerciseactive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exerciseassigned',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exerciseassigned',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of exercise assignation'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is the exercise active to perform?'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is the exercise fully completed?'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='period_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('By appointment as a mentor', 'Appointment')], max_length=30, verbose_name='exercise.availability.period'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='required_count',
            field=models.PositiveSmallIntegerField(verbose_name='exercise.availability.count'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of exercise assignation'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exerciseexpiration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exerciseexpiration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='failure_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Count of failure task performing'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='success_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count of success task performing'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='tracking_date',
            field=models.DateField(auto_now=True, verbose_name='Date for daily progress tracking'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='exercise.reward.amount'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='reward_type',
            field=models.CharField(choices=[('Per each case', 'Per Case'), ('For all cases', 'Complete')], max_length=30, verbose_name='exercise.reward.type'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='exercisetaskcount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exercisetaskcount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
