# Generated by Django 5.2.7 on 2025-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='examine',
            field=models.PositiveSmallIntegerField(default=16, help_text='Значение для смены стадии "Проверяю-Знаю"', verbose_name='Проверяю'),
        ),
    ]
