# Generated by Django 6.0.1 on 2026-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exercise performance log', 'verbose_name_plural': 'Exercise performance logs'},
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of exercise assignation'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is the exercise active to perform?'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is the exercise fully completed?'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='period_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('По назначено наставником', 'Appointment')], max_length=30, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of exercise assignation'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='failure_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Count of failure task performing'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='success_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count of success task performing'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='tracking_date',
            field=models.DateField(auto_now=True, verbose_name='Date for daily progress tracking'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='reward_type',
            field=models.CharField(choices=[('Per each case', 'Per Case'), ('For all cases', 'Complete')], max_length=30, verbose_name='exercise.reward.type'),
        ),
    ]
