# Generated by Django 6.0.1 on 2026-02-21 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseavailability',
            options={'verbose_name': 'Доступность упражнения', 'verbose_name_plural': 'Доступность упражнений'},
        ),
        migrations.AlterModelOptions(
            name='exercisereward',
            options={'verbose_name': 'Вознаграждение за упражнение', 'verbose_name_plural': 'Вознаграждения за упражнения'},
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во заданий'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('По назначено наставником', 'Appointment')], max_length=30, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='exerciseavailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_availabilities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь выполняющий упражнение'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='exercisereward',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorship', verbose_name='Упражнение при наставничестве'),
        ),
    ]
