# Generated by Django 5.2.7 on 2025-12-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='examine',
            field=models.PositiveSmallIntegerField(default=13, help_text='Значение для смены стадии "Проверяю-Знаю"', verbose_name='Проверяю'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='know',
            field=models.PositiveSmallIntegerField(default=17, help_text='Максимальное значение прогресса', verbose_name='Знаю'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='repeat',
            field=models.PositiveSmallIntegerField(default=10, help_text='Значение для смены стадии "Повторяю-Проверяю"', verbose_name='Повторяю'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='study',
            field=models.PositiveSmallIntegerField(default=7, help_text='Значение для смены стадий "Изучаю-Повторяю"', verbose_name='Изучаю'),
        ),
    ]
