"""Migration to create user balance tracking system."""

from django.db import migrations

# SQL for creating the balance table
CREATE_TABLE_SQL = """
CREATE TABLE users.balance (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL UNIQUE,
    total DECIMAL(11, 2),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users.customuser(id)
        ON DELETE CASCADE
);
"""

# SQL for reverse migration
DROP_TABLE_SQL = """
DROP TABLE IF EXISTS users.balance CASCADE;
"""

class Migration(migrations.Migration):
    """Migration to create user balance tracking table."""

    dependencies = [
        ('users', '0001_initial'),  # Contains users.customuser definition
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLE_SQL,
            reverse_sql=DROP_TABLE_SQL,
        )
    ]
