# Generated by Django 4.2 on 2024-06-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLearningStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_count', models.PositiveSmallIntegerField(default=0, help_text='The number of times the word was displayed to the user.')),
                ('word', models.OneToOneField(help_text='ID of the word being studied.', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='english.wordmodel')),
            ],
        ),
    ]
