# Generated by Django 4.2 on 2024-06-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_wordlearningstories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlearningstories',
            options={'ordering': ['display_count'], 'verbose_name': 'История изучения слов', 'verbose_name_plural': 'История изучения слов'},
        ),
    ]
