# Generated by Django 4.2.6 on 2024-01-10 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0002_alter_wordmodel_knowledge_assessment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordsfavoritesmodel',
            unique_together={('word', 'user')},
        ),
    ]
