# Generated by Django 4.2.14 on 2024-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_wordmodel_mentor_alter_wordmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'ordering': ['pk'], 'verbose_name': 'Словарь иностранных слов', 'verbose_name_plural': 'Словарь иностранных слов'},
        ),
        migrations.RenameField(
            model_name='wordmodel',
            old_name='knowledge_assessment',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='wordmodel',
            old_name='word_rus',
            new_name='russian_word',
        ),
        migrations.RenameField(
            model_name='worduserknowledgerelation',
            old_name='knowledge_assessment',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='wordmodel',
            name='word_eng',
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='foreign_word',
            field=models.CharField(default='word', help_text='Не более 75 символов.', max_length=75, verbose_name='Иностранное слово'),
            preserve_default=False,
        ),
    ]
