# Generated by Django 4.2.6 on 2023-12-17 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0002_sourcemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLabelRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.labelmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_eng', models.CharField(max_length=60, verbose_name='Слово на английском')),
                ('words_rus', models.CharField(max_length=60, verbose_name='Слово на русском')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='english.categorymodel', verbose_name='Категория')),
                ('labels', models.ManyToManyField(blank=True, related_name='labels', through='english.WordLabelRelation', to='english.labelmodel', verbose_name='Метки')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='english.lessonmodel', verbose_name='Тема урока')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='english.sourcemodel', verbose_name='Источник')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_added_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Англо-русский словарь',
                'verbose_name_plural': 'Англо-русские словари',
            },
        ),
        migrations.AddField(
            model_name='wordlabelrelation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.wordmodel'),
        ),
    ]
