# Generated by Django 4.2.6 on 2023-12-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_wordlabelrelation_wordmodel_wordlabelrelation_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'verbose_name': 'Англо-русский словарь', 'verbose_name_plural': 'Англо-русский словарь'},
        ),
        migrations.RenameField(
            model_name='lessonmodel',
            old_name='title',
            new_name='name',
        ),
    ]
