# Generated by Django 4.2.6 on 2024-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_wordsfavoritesmodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsfavoritesmodel',
            options={'verbose_name': 'Избранное слово', 'verbose_name_plural': 'Избранные слова'},
        ),
        migrations.AlterModelOptions(
            name='worduserknowledgerelation',
            options={'verbose_name': 'Оценка пользователем знания слова', 'verbose_name_plural': 'Оценки пользователем знания слова'},
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.CharField(blank=True, help_text='Описание не более 100 символов.', max_length=100, verbose_name='Описание.'),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='description',
            field=models.CharField(blank=True, help_text='Описание не более 100 слов.', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(help_text='Наименование не более 30 символов.', max_length=30, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(help_text='Имя не более 50 символов.', max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL-адрес источника.', max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
