# Generated by Django 4.2.6 on 2023-12-19 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_alter_wordmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labelmodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
