# Generated by Django 4.2.6 on 2024-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='description',
            field=models.CharField(blank=True, help_text='Описание не более 100 слов.', max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
