# Generated by Django 4.2.6 on 2023-12-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_alter_labelmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Источник'),
        ),
    ]
