# Generated by Django 4.2.6 on 2023-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_alter_sourcemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
