# Generated by Django 4.2.6 on 2024-02-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_alter_wordmodel_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlabelrelation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='wordlabelrelation',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordmodel',
            name='labels',
        ),
        migrations.DeleteModel(
            name='LabelModel',
        ),
        migrations.DeleteModel(
            name='WordLabelRelation',
        ),
    ]
