# Generated by Django 4.2.6 on 2023-12-21 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_alter_wordmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
