# Generated by Django 4.2.6 on 2024-02-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_remove_wordlabelrelation_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='english.lessonmodel', verbose_name='Тема урока'),
        ),
    ]
