# Generated by Django 4.2.6 on 2023-12-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_alter_wordmodel_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.PROTECT, to='english.categorymodel', verbose_name='Категория'),
        ),
    ]
