# Generated by Django 4.2.6 on 2023-12-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_alter_wordmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='words_eng',
            field=models.CharField(max_length=70, verbose_name='Слово на английском'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='words_rus',
            field=models.CharField(max_length=70, verbose_name='Слово на русском'),
        ),
    ]
