# Generated by Django 4.2.6 on 2023-12-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0013_alter_wordmodel_words_eng_alter_wordmodel_words_rus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordUserKnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_assessment', models.DecimalField(decimal_places=0, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.wordmodel')),
            ],
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='knowledge_assessment',
            field=models.ManyToManyField(blank=True, related_name='knowledge_assessment', through='english.WordUserKnowledgeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
