# Generated by Django 4.2.6 on 2024-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_remove_wordmodel_lesson_delete_lessonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
