# Generated by Django 4.2.6 on 2023-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_alter_wordmodel_words_eng_alter_wordmodel_words_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='words_eng',
            field=models.CharField(max_length=75, verbose_name='Слово на английском'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='words_rus',
            field=models.CharField(max_length=75, verbose_name='Слово на русском'),
        ),
    ]
