# Generated by Django 4.2.6 on 2023-12-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0014_alter_wordmodel_words_eng_alter_wordmodel_words_rus'),
        ('english', '0014_worduserknowledgerelation_and_more'),
    ]

    operations = [
    ]
