# Generated by Django 4.2.6 on 2024-02-24 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0014_alter_wordmodel_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worduserknowledgerelation',
            unique_together={('word', 'user')},
        ),
    ]
