# Generated by Django 4.2.6 on 2023-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_alter_worduserknowledgerelation_knowledge_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduserknowledgerelation',
            name='knowledge_assessment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
