# Generated by Django 4.2.6 on 2023-12-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0017_alter_worduserknowledgerelation_knowledge_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcemodel',
            options={'ordering': ['name'], 'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
    ]
