# Generated by Django 4.2.6 on 2024-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0018_sourcemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Описание не более 100 слов.', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
