# Generated by Django 4.2.6 on 2023-12-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0018_alter_sourcemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'ordering': ['words_eng'], 'verbose_name': 'Англо-русский словарь', 'verbose_name_plural': 'Англо-русский словарь'},
        ),
    ]
