# Generated by Django 4.2.6 on 2023-12-31 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0019_alter_wordmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='knowledge_assessment',
            field=models.ManyToManyField(blank=True, related_name='get_knowledge_assessment', through='english.WordUserKnowledgeRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_source', to='english.sourcemodel', verbose_name='Источник'),
        ),
    ]
