# Generated by Django 4.2.6 on 2024-04-08 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0019_alter_sourcemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.CharField(blank=True, help_text='Не более 100 символов.', max_length=100, verbose_name='Описание.'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(help_text='Не более 30 символов.', max_length=30, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='description',
            field=models.CharField(blank=True, help_text='Не более 100 символов.', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(help_text='Не более 50 символов.', max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL-адрес источника'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='english.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='words_eng',
            field=models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на английском'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='words_rus',
            field=models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на русском'),
        ),
    ]
