# Generated by Django 4.2.6 on 2023-12-31 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0020_alter_wordmodel_knowledge_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='knowledge_assessment',
            field=models.ManyToManyField(blank=True, through='english.WordUserKnowledgeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
