# Generated by Django 4.2.6 on 2024-01-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0027_alter_wordmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'ordering': ['pk'], 'verbose_name': 'Англо-русский словарь', 'verbose_name_plural': 'Англо-русский словарь'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='english.categorymodel', verbose_name='Категория'),
        ),
    ]
