# Generated by Django 4.2.14 on 2024-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathematicsAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение')], max_length=10)),
                ('first_operand', models.SmallIntegerField()),
                ('second_operand', models.SmallIntegerField()),
                ('user_solution', models.SmallIntegerField()),
                ('is_correctly', models.BooleanField(blank=True, null=True)),
                ('solution_time', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
