# Generated by Django 4.2.14 on 2025-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathematicsanalytic',
            options={'verbose_name': 'Решение задания пользователем', 'verbose_name_plural': 'Решения заданий пользователем'},
        ),
        migrations.AlterField(
            model_name='mathematicsanalytic',
            name='solution_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
