# Generated by Django 4.2.14 on 2025-02-16 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathematics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathematicsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение')], max_length=10)),
                ('operand1', models.SmallIntegerField()),
                ('operand2', models.SmallIntegerField()),
                ('answer', models.SmallIntegerField()),
                ('is_correctly', models.BooleanField(blank=True, null=True)),
                ('time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Решение задания пользователем',
                'verbose_name_plural': 'Решения заданий пользователем',
            },
        ),
        migrations.DeleteModel(
            name='MathematicsAnalytic',
        ),
    ]
