# Generated by Django 4.2.14 on 2025-02-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pointtransaction_transaction_and_more'),
        ('mathematics', '0003_mathematicstasks_delete_mathematicsanalytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathematicstasks',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='math', to='users.transaction', verbose_name='Начисление очков'),
        ),
    ]
