# Generated by Django 4.2.14 on 2025-02-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0004_mathematicstasks_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathematicstasks',
            old_name='calculation_type',
            new_name='exercise_type',
        ),
    ]
