# Generated by Django 4.2.14 on 2025-02-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0005_rename_calculation_type_mathematicstasks_exercise_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathematicstasks',
            old_name='exercise_type',
            new_name='exercise',
        ),
    ]
