# Generated by Django 4.2 on 2024-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_glossarycategory_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'verbose_name': 'Глоссарий', 'verbose_name_plural': 'Глоссарий'},
        ),
        migrations.AlterModelOptions(
            name='glossarycategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
