# Generated by Django 4.2 on 2024-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0008_glossarycategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarycategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='glossarycategory',
            name='email',
            field=models.URLField(blank=True),
        ),
    ]
