# Generated by Django 4.2 on 2024-07-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0011_alter_glossary_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossarycategory',
            old_name='email',
            new_name='url',
        ),
    ]
