# Generated by Django 4.2.14 on 2024-10-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, verbose_name='Термин')),
                ('translate', models.CharField(blank=True, max_length=50, verbose_name='Перевод')),
                ('definition', models.CharField(blank=True, max_length=250, verbose_name='Определение')),
                ('interpretation', models.TextField(blank=True, verbose_name='Толкование')),
                ('progress', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Глоссарий',
                'verbose_name_plural': 'Глоссарий',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='GlossaryParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC')),
                ('period_end_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT')),
                ('progress', models.CharField(choices=[('S', 'Изучаю'), ('R', 'Повторяю'), ('E', 'Проверяю'), ('K', 'Знаю')], default='S')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.glossarycategory')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Настройки изучения терминов пользователей',
            },
        ),
    ]
