# Generated by Django 4.2 on 2024-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_glossarycategory_glossary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossarycategory',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
