# Generated by Django 4.2.14 on 2024-11-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_alter_termsource_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryparams',
            name='count_first',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='glossaryparams',
            name='count_last',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='glossaryparams',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='glossaryparams',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.termsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='glossaryparams',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Таймаут'),
        ),
        migrations.AlterField(
            model_name='glossaryparams',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.glossarycategory'),
        ),
        migrations.AlterField(
            model_name='glossaryparams',
            name='period_end_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT', max_length=2, verbose_name='Добавлено до'),
        ),
        migrations.AlterField(
            model_name='glossaryparams',
            name='period_start_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC', max_length=2, verbose_name='Добавлено после'),
        ),
        migrations.AlterField(
            model_name='glossaryparams',
            name='progress',
            field=models.CharField(choices=[('S', 'Изучаю'), ('R', 'Повторяю'), ('E', 'Проверяю'), ('K', 'Знаю')], default='S', max_length=1, verbose_name='Уровень знания'),
        ),
    ]
