# Generated by Django 4.2 on 2024-06-10 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_alter_glossary_category_alter_glossary_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.date(2024, 6, 10), verbose_name='Добавлено'),
            preserve_default=False,
        ),
    ]
