# Generated by Django 4.2.14 on 2024-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_alter_glossaryparams_period_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
