# Generated by Django 4.2.14 on 2024-11-11 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0010_glossary_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glossary',
            new_name='Term',
        ),
        migrations.RenameModel(
            old_name='GlossaryCategory',
            new_name='TermCategory',
        ),
    ]
