# Generated by Django 4.2.14 on 2024-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0011_rename_glossary_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='example',
            field=models.TextField(blank=True, verbose_name='Пример'),
        ),
        migrations.AddField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL-адрес определения'),
        ),
    ]
