# Generated by Django 4.2.14 on 2024-09-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_wordmodel_mentor_alter_wordmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0013_glossaryexercisesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryexercisesettings',
            options={'verbose_name': 'Настройки изучения терминов', 'verbose_name_plural': 'Настройки изучения терминов'},
        ),
        migrations.AlterField(
            model_name='glossaryexercisesettings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='english.categorymodel'),
        ),
        migrations.AlterField(
            model_name='glossaryexercisesettings',
            name='period_end_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default=('DT', 'Сегодня')),
        ),
        migrations.AlterField(
            model_name='glossaryexercisesettings',
            name='period_start_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default=('NC', 'Добавлено')),
        ),
        migrations.AlterField(
            model_name='glossaryexercisesettings',
            name='progres',
            field=models.CharField(choices=[('S', 'Изучаю'), ('R', 'Повторяю'), ('E', 'Проверяю'), ('K', 'Знаю')], default=('S', 'Изучаю')),
        ),
        migrations.AlterField(
            model_name='glossaryexercisesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
