# Generated by Django 4.2.14 on 2024-12-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0013_glossaryparams_is_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryparams',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='glossaryparams',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
