# Generated by Django 4.2.14 on 2024-09-07 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_wordmodel_mentor_alter_wordmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0014_alter_glossaryexercisesettings_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlossaryExerciseSettings',
            new_name='GlossaryExerciseParameters',
        ),
    ]
