# Generated by Django 4.2.14 on 2025-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0014_glossaryparams_is_last_alter_glossaryparams_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryparams',
            name='has_timeout',
            field=models.BooleanField(default=True),
        ),
    ]
