# Generated by Django 4.2.14 on 2024-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0015_rename_glossaryexercisesettings_glossaryexerciseparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarycategory',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
