# Generated by Django 4.2.14 on 2025-01-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0016_alter_glossaryparams_count_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
