# Generated by Django 4.2.14 on 2024-09-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0017_alter_glossaryexerciseparameters_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryExerciseParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT')),
                ('period_end_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC')),
                ('progres', models.CharField(choices=[('S', 'Изучаю'), ('R', 'Повторяю'), ('E', 'Проверяю'), ('K', 'Знаю')], default='S')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Настройки изучения терминов пользователей',
            },
        ),
        migrations.RenameField(
            model_name='glossarycategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='glossarycategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GlossaryExerciseParameters',
        ),
        migrations.AddField(
            model_name='glossaryexerciseparams',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.glossarycategory'),
        ),
        migrations.AddField(
            model_name='glossaryexerciseparams',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
