# Generated by Django 4.2.14 on 2024-09-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0018_glossaryexerciseparams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progres', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.glossary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс',
                'unique_together': {('user', 'term')},
            },
        ),
    ]
