# Generated by Django 4.2.14 on 2024-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0020_glossary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'ordering': ['pk'], 'verbose_name': 'Глоссарий', 'verbose_name_plural': 'Глоссарий'},
        ),
        migrations.AddField(
            model_name='glossary',
            name='progres',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='glossaryexerciseparams',
            name='period_end_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT'),
        ),
        migrations.AlterField(
            model_name='glossaryexerciseparams',
            name='period_start_date',
            field=models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC'),
        ),
    ]
