# Generated by Django 4.2.14 on 2024-09-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0021_alter_glossary_options_glossary_progres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='progres',
            new_name='progress',
        ),
    ]
