# Generated by Django 4.2.14 on 2024-09-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0022_rename_progres_glossary_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossaryexerciseparams',
            old_name='progres',
            new_name='progress',
        ),
    ]
