# Generated by Django 4.2.14 on 2024-09-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0023_rename_progres_glossaryexerciseparams_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossaryprogress',
            old_name='progres',
            new_name='progress',
        ),
    ]
