# Generated by Django 4.2.14 on 2024-10-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0024_rename_progres_glossaryprogress_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlossaryProgress',
        ),
    ]
