# Generated by Django 4.2 on 2024-06-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishtasksettings',
            options={'verbose_name': 'Настройки "Изучаем слова"', 'verbose_name_plural': 'Настройки "Изучаем слова"'},
        ),
    ]
