# Generated by Django 4.2.14 on 2024-07-31 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_guardianship'),
        ('task', '0002_alter_englishtasksettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathematicalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение'), ('div', 'Деление')], max_length=10)),
                ('first_operand', models.SmallIntegerField()),
                ('second_operand', models.SmallIntegerField()),
                ('user_solution', models.SmallIntegerField()),
                ('is_correctly', models.BooleanField(blank=True, null=True)),
                ('solution_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.SmallIntegerField()),
                ('write_off', models.SmallIntegerField()),
                ('balance', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardianship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guardianship')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.mathematicalexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
