# Generated by Django 4.2.14 on 2024-08-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_points_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='guardianship',
        ),
    ]
