# Generated by Django 4.2.14 on 2024-08-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_points_guardianship'),
        ('users', '0004_mentorship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='mentorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mentorship'),
        ),
    ]
