# Generated by Django 4.2.14 on 2024-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_points_mentorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathematicalexercise',
            name='first_operand',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mathematicalexercise',
            name='second_operand',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mathematicalexercise',
            name='user_solution',
            field=models.SmallIntegerField(),
        ),
    ]
