# Generated by Django 4.2.14 on 2024-08-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_mathematicalexercise_first_operand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.mathematicalexercise'),
        ),
    ]
