# Generated by Django 5.2.7 on 2025-11-13 22:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на английском')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Английское слово',
                'verbose_name_plural': 'Английские слова',
                'db_table': 'lang_word_english',
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='LangCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'lang_category',
            },
        ),
        migrations.CreateModel(
            name='LangExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(help_text='Exercise in discipline', on_delete=django.db.models.deletion.CASCADE, to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'db_table': 'lang_exercise',
            },
        ),
        migrations.CreateModel(
            name='LangLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Лейбл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лейбл',
                'verbose_name_plural': 'Лейблы',
                'db_table': 'lang_label',
            },
        ),
        migrations.CreateModel(
            name='NativeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на родном языке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Слово родного языка',
                'verbose_name_plural': 'Слова родного языка',
                'db_table': 'lang_word_native',
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.englishword', verbose_name='Слово на английском')),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.nativeword', verbose_name='Слово на родном языке')),
            ],
            options={
                'verbose_name': 'Перевод слова на английский',
                'verbose_name_plural': 'Переводы слов на английский',
                'db_table': 'lang_translation_english',
            },
        ),
        migrations.CreateModel(
            name='EnglishProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12, message='Значение прогресса не должно превышать 12')], verbose_name='Прогресс изучения')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.englishtranslation', verbose_name='Перевод родной-английский')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс',
                'db_table': 'lang_progress_english',
                'constraints': [models.UniqueConstraint(fields=('user', 'translation'), name='progress_english_unique_user_translation'), models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 12)), name='progress_english_range_check')],
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальное количество слов')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_params', to='lang.langcategory', verbose_name='Категория')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_params', to='lang.langlabel', verbose_name='Лейбл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_params', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметр изучения слов',
                'verbose_name_plural': 'Параметры изучения слов',
                'db_table': 'lang_params',
                'constraints': [models.UniqueConstraint(fields=('user',), name='word_study_params_unique_user_name')],
            },
        ),
    ]
