# Generated by Django 6.0.1 on 2026-03-21 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='EnglishAssignedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Назначенное упражнение по английскому',
                'verbose_name_plural': 'Назначенные упражнения по английскому',
                'db_table': 'lang_assigned_english_exercise',
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс изучения')),
            ],
            options={
                'verbose_name': 'Перевод слова на английский',
                'verbose_name_plural': 'Переводы слов на английский',
                'db_table': 'lang_english_translation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Translation exercise',
                'verbose_name_plural': 'Translation exercises',
                'db_table': 'lang_english_exercise_translation_progress',
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Progress value')),
            ],
            options={
                'verbose_name': 'Translation study progress',
                'verbose_name_plural': 'Translation study progress',
                'db_table': 'lang_english_translation_progress',
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslationStudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Progress value')),
            ],
            options={
                'verbose_name': 'Translation study progress for exercise',
                'verbose_name_plural': 'Translation study progress for exercise',
                'db_table': 'lang_english_translation_exercise_progress',
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на английском')),
            ],
            options={
                'verbose_name': 'Английское слово',
                'verbose_name_plural': 'Английские слова',
                'db_table': 'lang_english_word',
            },
        ),
        migrations.CreateModel(
            name='ExerciseConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_study', models.BooleanField(blank=True, default=True, help_text='Selected words for study', null=True, verbose_name='Study')),
                ('is_repeat', models.BooleanField(blank=True, default=True, help_text='Selected words for repetition', null=True, verbose_name='Repeat')),
                ('is_examine', models.BooleanField(blank=True, default=True, help_text='Select words to examine', null=True, verbose_name='Examine')),
                ('is_know', models.BooleanField(blank=True, default=False, help_text='Select the learned words', null=True, verbose_name='Know')),
            ],
            options={
                'verbose_name': 'Word learning parameter',
                'verbose_name_plural': 'Word learning parameters',
                'db_table': 'lang_parameters',
            },
        ),
        migrations.CreateModel(
            name='LanguageExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Маркер')),
            ],
            options={
                'verbose_name': 'Маркер',
                'verbose_name_plural': 'Маркеры',
            },
        ),
        migrations.CreateModel(
            name='MentorshipEnglishRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правило английского языка для изучения в наставничестве',
                'verbose_name_plural': 'Правила английского языка для изучения в наставничестве',
                'db_table': 'lang_english_mentorship_rule',
                'ordering': ['mentorship', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NativeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('word', models.CharField(max_length=70, verbose_name='Слово на родном языке')),
            ],
            options={
                'verbose_name': 'Слово родного языка',
                'verbose_name_plural': 'Слова родного языка',
                'db_table': 'lang_word_native',
            },
        ),
        migrations.CreateModel(
            name='PresentationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('question_timeout', models.PositiveSmallIntegerField(blank=True, default=3, help_text='From 1 to 300 seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Task read time (sec)')),
                ('answer_timeout', models.PositiveSmallIntegerField(blank=True, default=3, help_text='From 1 to 300 seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Task completion time (sec)')),
            ],
            options={
                'verbose_name': 'Presentation settings',
                'verbose_name_plural': 'Presentation settings',
                'db_table': 'lang_presentation_settings',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Правило')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание правила')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Тег правила')),
                ('code', models.CharField(blank=True, help_text='Уникальный буквенно-цифровой код (например, PROC-001)', max_length=50, null=True, unique=True, verbose_name='Код правила')),
            ],
            options={
                'verbose_name': 'Правило пользователя',
                'verbose_name_plural': 'Правила пользователя',
                'db_table': 'lang_rule',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ordinal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('exception_content', models.TextField(blank=True, null=True, verbose_name='Исключение пункта правила')),
            ],
            options={
                'verbose_name': 'Пункт правила',
                'verbose_name_plural': 'Пункты правил',
                'db_table': 'lang_rule_clause',
                'ordering': ['rule', 'ordinal', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('example_type', models.CharField(choices=[('example', 'Пример'), ('exception', 'Исключение')], default='example', help_text='Тип примера пункта правила: "пример"/"исключение"', max_length=10, verbose_name='Тип примера')),
            ],
            options={
                'verbose_name': 'Пример/исключение слова пункта правила',
                'verbose_name_plural': 'Примеры/исключения слов пунктов правил',
                'db_table': 'lang_rule_translation_example',
                'ordering': ['clause', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Исключение правила',
                'verbose_name_plural': 'Исключения правил',
                'db_table': 'lang_rule_exception',
                'ordering': ['rule', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleTaskExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('example_type', models.CharField(choices=[('example', 'Пример'), ('exception', 'Исключение')], default='example', help_text='Тип примера пункта правила: "пример"/"исключение"', max_length=10, verbose_name='Тип примера')),
            ],
            options={
                'verbose_name': 'Пример/исключение задания пункта правила',
                'verbose_name_plural': 'Примеры/исключения заданий пунктов правил',
                'db_table': 'lang_rule_task_example',
                'ordering': ['clause', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Маркировка перевода',
                'verbose_name_plural': 'Маркировки переводов',
                'db_table': 'lang_translation_mark',
            },
        ),
        migrations.CreateModel(
            name='TranslationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('display_order', models.CharField(blank=True, choices=[('from_native', 'С родного языка'), ('to_native', 'На родной язык'), ('random', 'Случайный порядок')], default='to_native', max_length=20, null=True, verbose_name='Порядок перевода')),
                ('word_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальное количество слов')),
            ],
            options={
                'verbose_name': 'Настройки изучения переводов',
                'verbose_name_plural': 'Настройки изучения переводов',
                'db_table': 'lang_translation_settings',
            },
        ),
    ]
