# Generated by Django 6.0.1 on 2026-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsetting',
            name='translation_order',
        ),
        migrations.AddField(
            model_name='translationsetting',
            name='display_order',
            field=models.CharField(blank=True, choices=[('from_native', 'С родного языка'), ('to_native', 'На родной язык'), ('random', 'Случайный порядок')], default='to_native', max_length=20, null=True, verbose_name='Порядок перевода'),
        ),
    ]
