# Generated by Django 5.2.7 on 2025-10-29 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальное количество слов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_params', to='lang.langcategory', verbose_name='Категория')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_params', to='lang.langlabel', verbose_name='Лейбл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_params', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметр изучения слов',
                'verbose_name_plural': 'Параметры изучения слов',
                'db_table': 'lang_params',
            },
        ),
    ]
