"""Migration to create Transaction table with PostgreSQL inheritance.

Creates:
1. Table `lang.transaction` inheriting from `main.transaction`
2. Automatic ID generation using PostgreSQL identity column

Important notes:
- Inherits all columns from parent table `main.transaction`
- Child table can add additional columns
- CASCADE used in reverse migration to ensure proper cleanup
"""

from django.db import migrations

# SQL for creating the inherited transaction table
CREATE_TABLE_SQL = """
CREATE TABLE lang.transaction (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users.customuser(id)
        ON DELETE CASCADE
) INHERITS (main.transaction);
"""

# SQL for reverse migration
DROP_TABLE_SQL = """
DROP TABLE IF EXISTS lang.transaction CASCADE;
"""


class Migration(migrations.Migration):
    """Migration to create language transaction table with inheritance."""

    dependencies = [
        ('lang', '0001_create_exercise'),  # Previous migration
        ('main', '0002_create_base_transaction'),  # Parent table must exist
        ('users', '0001_initial'),  # Required for user reference
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLE_SQL,
            reverse_sql=DROP_TABLE_SQL,
        ),
    ]
