# Generated by Django 5.2.7 on 2025-11-13 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishprogress',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='englishprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Обновлено'),
            preserve_default=False,
        ),
    ]
