# Generated by Django 6.0.1 on 2026-02-25 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('lang', '0001_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.progress', verbose_name='Вариант прогресса'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='start_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_params', to='core.period', verbose_name='Период с'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='word_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentation_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='rule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.source', verbose_name='Источник правила'),
        ),
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь добавивший правило'),
        ),
        migrations.AddField(
            model_name='mentorshipenglishrule',
            name='rule',
            field=models.ForeignKey(help_text='Правило для изучения в наставничестве', on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='lang.rule', verbose_name='Правило для изучения'),
        ),
        migrations.AddField(
            model_name='ruleclause',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lang.ruleclause', verbose_name='Родительский пункт'),
        ),
        migrations.AddField(
            model_name='ruleclause',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='lang.rule', verbose_name='Правило'),
        ),
        migrations.AddField(
            model_name='ruleclause',
            name='user',
            field=models.ForeignKey(help_text='Пользователь (собственник) добавивший пункт', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ruleexample',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_translation_examples', to='lang.ruleclause', verbose_name='Пункт правила языка'),
        ),
        migrations.AddField(
            model_name='ruleexample',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_rule_examples', to='lang.englishtranslation', verbose_name='Перевод вопроса'),
        ),
        migrations.AddField(
            model_name='ruleexample',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, добавивший пример/исключение', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ruleexception',
            name='answer_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_answer_translation', to='lang.englishtranslation', verbose_name='Перевод ответа'),
        ),
        migrations.AddField(
            model_name='ruleexception',
            name='question_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_question_translation', to='lang.englishtranslation', verbose_name='Перевод вопроса'),
        ),
        migrations.AddField(
            model_name='ruleexception',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='lang.rule', verbose_name='Правило'),
        ),
        migrations.AddField(
            model_name='ruleexception',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, добавивший исключение', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ruletaskexample',
            name='answer_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rule_answers', to='lang.englishtranslation', verbose_name='Перевод ответа'),
        ),
        migrations.AddField(
            model_name='ruletaskexample',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_task_examples', to='lang.ruleclause', verbose_name='Пункт правила языка'),
        ),
        migrations.AddField(
            model_name='ruletaskexample',
            name='question_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rule_questions', to='lang.englishtranslation', verbose_name='Перевод вопроса'),
        ),
        migrations.AddField(
            model_name='ruletaskexample',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, добавивший пример/исключение', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='translationmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.mark', verbose_name='Маркер'),
        ),
        migrations.AddField(
            model_name='translationmark',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_translation_marks', to='lang.englishtranslation', verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='englishtranslation',
            name='marks',
            field=models.ManyToManyField(blank=True, through='lang.TranslationMark', through_fields=('translation', 'mark'), to='lang.mark', verbose_name='Маркеры'),
        ),
        migrations.AddField(
            model_name='translationsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_translation_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='englishtranslationprogress',
            unique_together={('user', 'translation')},
        ),
        migrations.AlterUniqueTogether(
            name='englishword',
            unique_together={('user', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='englishtranslationexercise',
            unique_together={('exercise', 'translation')},
        ),
        migrations.AlterUniqueTogether(
            name='nativeword',
            unique_together={('user', 'word')},
        ),
        migrations.AddConstraint(
            model_name='parameters',
            constraint=models.UniqueConstraint(fields=('user',), name='lang_parameters_unique_user_name'),
        ),
        migrations.AddConstraint(
            model_name='presentationsettings',
            constraint=models.UniqueConstraint(fields=('user',), name='lang_presentation_settings_unique_user_name'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipenglishrule',
            unique_together={('mentorship', 'rule')},
        ),
        migrations.AlterUniqueTogether(
            name='ruleclause',
            unique_together={('rule', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='ruleexample',
            unique_together={('clause', 'translation')},
        ),
        migrations.AlterUniqueTogether(
            name='ruleexception',
            unique_together={('question_translation', 'answer_translation')},
        ),
        migrations.AlterUniqueTogether(
            name='ruletaskexample',
            unique_together={('clause', 'question_translation', 'answer_translation')},
        ),
        migrations.AlterUniqueTogether(
            name='translationmark',
            unique_together={('translation', 'mark')},
        ),
        migrations.AddConstraint(
            model_name='translationsetting',
            constraint=models.UniqueConstraint(fields=('user',), name='lang_translation_settings_unique_user_name'),
        ),
    ]
