# Generated by Django 5.2.4 on 2025-07-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langexercise',
            options={'managed': False, 'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
    ]
