# Generated by Django 6.0.1 on 2026-04-12 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('question_timeout', models.PositiveSmallIntegerField(blank=True, default=3, help_text='From 1 to 300 seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Task read time (sec)')),
                ('answer_timeout', models.PositiveSmallIntegerField(blank=True, default=3, help_text='From 1 to 300 seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Task completion time (sec)')),
            ],
            options={
                'verbose_name': 'Presentation configuration',
                'verbose_name_plural': 'Presentation configuration',
                'db_table': 'lang_presentation_config',
            },
        ),
        migrations.RemoveConstraint(
            model_name='presentationsettings',
            name='lang_presentation_settings_unique_user_name',
        ),
        migrations.AddField(
            model_name='presentationconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentation_configuration', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RemoveField(
            model_name='presentationsettings',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='presentationconfig',
            constraint=models.UniqueConstraint(fields=('user',), name='lang_presentation_config_unique_user_name'),
        ),
        migrations.DeleteModel(
            name='PresentationSettings',
        ),
    ]
