# Generated by Django 5.2.7 on 2025-12-17 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='is_examine',
            field=models.BooleanField(blank=True, default=True, help_text='Выбрать слова для проверки', null=True, verbose_name='Проверяю'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='is_know',
            field=models.BooleanField(blank=True, default=False, help_text='Выбрать выученные слова', null=True, verbose_name='Знаю'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=True, help_text='Выбрать слова для повторения', null=True, verbose_name='Повторяю'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='is_study',
            field=models.BooleanField(blank=True, default=True, help_text='Выбрать слова для изучения', null=True, verbose_name='Изучаю'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.progress', verbose_name='Вариант прогресса'),
        ),
        migrations.AlterField(
            model_name='presentationsettings',
            name='answer_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Время не может быть отрицательным')], verbose_name='Время для ответа (сек)'),
        ),
        migrations.AlterField(
            model_name='presentationsettings',
            name='question_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Время не может быть отрицательным')], verbose_name='Время для вопроса (сек)'),
        ),
        migrations.AlterField(
            model_name='translationsetting',
            name='translation_order',
            field=models.CharField(blank=True, choices=[('from_native', 'С родного языка'), ('to_native', 'На родной язык'), ('random', 'Случайный порядок')], default='to_native', max_length=20, null=True, verbose_name='Порядок перевода'),
        ),
    ]
