# Generated by Django 5.2.7 on 2025-11-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='order',
        ),
        migrations.AddField(
            model_name='params',
            name='translation_order',
            field=models.CharField(blank=True, choices=[('from_native', 'С родного языка'), ('to_native', 'На родной язык'), ('random', 'Случайный порядок')], default='to_native', help_text='Направление перевода при изучении слов', max_length=20, null=True, verbose_name='Порядок перевода'),
        ),
    ]
