# Generated by Django 5.2.7 on 2025-12-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtranslation',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс изучения'),
        ),
        migrations.DeleteModel(
            name='EnglishProgress',
        ),
    ]
