# Generated by Django 6.0 on 2026-01-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleexample',
            options={'ordering': ['clause', 'created_at'], 'verbose_name': 'Пример/исключение слова пункта правила', 'verbose_name_plural': 'Примеры/исключения слов пунктов правил'},
        ),
        migrations.AlterModelOptions(
            name='ruletaskexample',
            options={'ordering': ['clause', 'created_at'], 'verbose_name': 'Пример/исключение задания пункта правила', 'verbose_name_plural': 'Примеры/исключения заданий пунктов правил'},
        ),
    ]
