# Generated by Django 6.0 on 2026-01-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='englishtranslation',
            old_name='english',
            new_name='foreign',
        ),
    ]
