# Generated by Django 6.0.1 on 2026-01-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_remove_translationsetting_translation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationmark',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_translation_marks', to='lang.englishtranslation', verbose_name='Перевод'),
        ),
    ]
