# Generated by Django 5.2.7 on 2025-10-29 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_params', to='lang.langcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='params',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_params', to='lang.langlabel', verbose_name='Лейбл'),
        ),
    ]
