# Generated by Django 5.2.7 on 2025-10-29 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_alter_params_category_alter_params_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='params',
            constraint=models.UniqueConstraint(fields=('user',), name='word_study_params_unique_user_name'),
        ),
    ]
