# Generated by Django 6.0 on 2026-01-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_alter_ruleexample_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruletaskexample',
            unique_together={('clause', 'question_translation', 'answer_translation')},
        ),
    ]
