# Generated by Django 6.0.1 on 2026-01-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0004_alter_ruletaskexample_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishmark',
            name='user',
        ),
    ]
