# Generated by Django 6.0.1 on 2026-04-25 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('lang', '0004_presentationsettings_and_more'),
        ('study', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseconditions',
            options={'verbose_name': 'Word learning conditions', 'verbose_name_plural': 'Word learning conditions'},
        ),
        migrations.RemoveConstraint(
            model_name='exerciseconditions',
            name='lang_parameters_unique_user_name',
        ),
        migrations.AlterField(
            model_name='exerciseconditions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_conditions', to='lang.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='exerciseconditions',
            name='end_period',
            field=models.ForeignKey(blank=True, help_text='Added before data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_periods', to='core.period', verbose_name='End period'),
        ),
        migrations.AlterField(
            model_name='exerciseconditions',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_conditions', to='lang.mark', verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='exerciseconditions',
            name='start_period',
            field=models.ForeignKey(blank=True, help_text='Added after data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_periods', to='core.period', verbose_name='Start period'),
        ),
        migrations.AlterField(
            model_name='exerciseconditions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conditions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='exerciseconditions',
            constraint=models.UniqueConstraint(fields=('user',), name='lang_exercise_configuration_unique_user_name'),
        ),
        migrations.AlterModelTable(
            name='exerciseconditions',
            table='lang_exercise_configuration',
        ),
    ]
