# Generated by Django 6.0.1 on 2026-01-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0005_remove_englishmark_user'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='langexercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создавший упражнение'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='langexercise',
            unique_together={('name', 'user')},
        ),
        migrations.CreateModel(
            name='EnglishAssignedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.langexercise', verbose_name='Упражнение')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorship', verbose_name='Наставничество')),
            ],
            options={
                'verbose_name': 'Назначенное упражнение по английскому',
                'verbose_name_plural': 'Назначенные упражнения по английскому',
                'db_table': 'lang_assigned_english_exercise',
            },
        ),
        migrations.CreateModel(
            name='EnglishExerciseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.langexercise', verbose_name='Упражнение')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.englishtranslation', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Перевод упражнения',
                'verbose_name_plural': 'Переводы упражнения',
                'db_table': 'lang_english_exercise_translation',
                'unique_together': {('exercise', 'translation')},
            },
        ),
        migrations.CreateModel(
            name='EnglishTranslationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.englishtranslation', verbose_name='Перевод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс изучения перевода',
                'verbose_name_plural': 'Прогресс изучения переводов',
                'db_table': 'lang_english_translation_progress',
                'unique_together': {('user', 'translation')},
            },
        ),
    ]
