# Generated by Django 4.2 on 2024-06-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 30 символов.', max_length=30, verbose_name='Наименование категории')),
                ('description', models.CharField(blank=True, help_text='Не более 100 символов.', max_length=100, verbose_name='Описание.')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 50 символов.', max_length=50, verbose_name='Источник')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL-адрес источника')),
                ('description', models.CharField(blank=True, help_text='Не более 100 символов.', max_length=100, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_eng', models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на английском')),
                ('word_rus', models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на русском')),
                ('word_count', models.CharField(choices=[('NC', 'Любое количество слов'), ('OW', 'Слово'), ('CB', 'Словосочетание'), ('PS', 'Часть предложения'), ('ST', 'Предложение')], default='NC', max_length=2, verbose_name='Количество слов')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='english.categorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Англо-русский словарь',
                'verbose_name_plural': 'Англо-русский словарь',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WordUserKnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_assessment', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.wordmodel')),
            ],
            options={
                'verbose_name': 'Оценка пользователем знания слова',
                'verbose_name_plural': 'Оценки пользователем знания слова',
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WordsFavoritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.wordmodel')),
            ],
            options={
                'verbose_name': 'Избранное слово',
                'verbose_name_plural': 'Избранные слова',
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='word_favorites', through='english.WordsFavoritesModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='knowledge_assessment',
            field=models.ManyToManyField(blank=True, related_name='word_knowledge', through='english.WordUserKnowledgeRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_source', to='english.sourcemodel', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WordLearningStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_count', models.PositiveSmallIntegerField(default=0, help_text='The number of times the word was displayed to the user.')),
                ('word', models.OneToOneField(help_text='ID of the word being studied.', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='english.wordmodel')),
            ],
            options={
                'verbose_name': 'История изучения слов',
                'verbose_name_plural': 'История изучения слов',
                'ordering': ['display_count'],
            },
        ),
    ]
