# Generated by Django 5.2.7 on 2025-12-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Термин')),
                ('definition', models.CharField(max_length=250, verbose_name='Определение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion', models.CharField(max_length=300, verbose_name='Утверждение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Утверждение о термине',
                'verbose_name_plural': 'Утверждения о термине',
                'ordering': ['-created_at'],
            },
        ),
    ]
