# Generated by Django 4.2.14 on 2025-01-24 02:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Назначенное слово для изучения',
                'verbose_name_plural': 'Назначенные слова для изучения',
            },
        ),
        migrations.CreateModel(
            name='TranslateParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_timeout', models.BooleanField(default=True)),
                ('timeout', models.PositiveSmallIntegerField(default=5, verbose_name='Таймаут')),
                ('favorites', models.BooleanField(default=False, verbose_name='Избранное')),
                ('progress', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=['S'], size=None, verbose_name='Уровень знания')),
                ('period_start_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC', verbose_name='Добавлено после')),
                ('period_end_date', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT', max_length=2, verbose_name='Добавлено до')),
                ('is_first', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
                ('count_first', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('count_last', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('order', models.CharField(choices=[('RN', 'Случайный порядок'), ('TN', 'На родной'), ('FN', 'С родного')], default='TN', max_length=2, verbose_name='Порядок перевода')),
            ],
            options={
                'verbose_name': 'Настройки "Изучаем слова"',
                'verbose_name_plural': 'Настройки "Изучаем слова"',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на иностранном')),
                ('native_word', models.CharField(help_text='Не более 75 символов.', max_length=75, verbose_name='Слово на родном')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Словарь иностранных слов',
                'verbose_name_plural': 'Словарь иностранных слов',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WordAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_count', models.PositiveSmallIntegerField(default=0, help_text='The number of times the word was displayed to the user.')),
            ],
            options={
                'verbose_name': 'История изучения слов',
                'verbose_name_plural': 'История изучения слов',
                'ordering': ['display_count'],
            },
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 30 символов.', max_length=30, verbose_name='Наименование категории')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное слово',
                'verbose_name_plural': 'Избранные слова',
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'verbose_name': 'Оценка пользователем знания слова',
                'verbose_name_plural': 'Оценки пользователем знания слова',
            },
        ),
        migrations.CreateModel(
            name='WordSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 50 символов.', max_length=50, verbose_name='Источник')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL-адрес источника')),
                ('description', models.CharField(blank=True, help_text='Не более 100 символов.', max_length=100, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
