# Generated by Django 4.2.14 on 2024-10-05 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foreign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.word'),
        ),
        migrations.AddField(
            model_name='wordparams',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='wordparams',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='wordparams',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordfavorites',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.word'),
        ),
        migrations.AddField(
            model_name='wordcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordanalytics',
            name='word',
            field=models.OneToOneField(help_text='ID of the word being studied.', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='foreign.word'),
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='word',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='word_favorites', through='foreign.WordFavorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_word', to=settings.AUTH_USER_MODEL, verbose_name='Наставник, который добавил слово.'),
        ),
        migrations.AddField(
            model_name='word',
            name='progress',
            field=models.ManyToManyField(blank=True, related_name='word_knowledge', through='foreign.WordProgress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_source', to='foreign.wordsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который изучает слово'),
        ),
        migrations.AlterUniqueTogether(
            name='wordprogress',
            unique_together={('word', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='wordfavorites',
            unique_together={('word', 'user')},
        ),
    ]
