# Generated by Django 4.2.14 on 2025-01-24 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.word'),
        ),
        migrations.AddField(
            model_name='wordfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordfavorites',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.word'),
        ),
        migrations.AddField(
            model_name='wordcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordanalytics',
            name='word',
            field=models.OneToOneField(help_text='ID of the word being studied.', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='foreign.word'),
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='word',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='word_favorites', through='foreign.WordFavorites', to=settings.AUTH_USER_MODEL, verbose_name='Является ли слово избранным'),
        ),
        migrations.AddField(
            model_name='word',
            name='progress',
            field=models.ManyToManyField(blank=True, related_name='word_knowledge', through='foreign.WordProgress', to=settings.AUTH_USER_MODEL, verbose_name='Прогресс изучения слова'),
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_source', to='foreign.wordsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который добавил слово'),
        ),
        migrations.AddField(
            model_name='translateparams',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='translateparams',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='translateparams',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedword',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_student', to=settings.AUTH_USER_MODEL, verbose_name='Назначено слово студенту'),
        ),
        migrations.AddField(
            model_name='assignedword',
            name='word',
            field=models.ManyToManyField(blank=True, related_name='assigned_word', to='foreign.word', verbose_name='Назначенное слово'),
        ),
        migrations.AlterUniqueTogether(
            name='wordprogress',
            unique_together={('word', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='wordfavorites',
            unique_together={('word', 'user')},
        ),
    ]
