# Generated by Django 4.2.14 on 2024-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateparams',
            name='count_first',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество первых добавленных слов'),
        ),
        migrations.AddField(
            model_name='translateparams',
            name='count_last',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество последних добавленных слов'),
        ),
    ]
