# Generated by Django 4.2.14 on 2024-10-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_order', models.CharField(choices=[('RN', 'Перевод в случайном порядке'), ('TR', 'Перевод на русский язык'), ('FR', 'Перевод с русского язык')], default='RN', max_length=2, verbose_name='Порядок перевода')),
                ('timeout', models.PositiveSmallIntegerField(default=5, verbose_name='Таймаут')),
                ('favorites', models.BooleanField(default=False, verbose_name='Избранное')),
                ('progress', models.CharField(choices=[('S', 'Изучаю'), ('R', 'Повторяю'), ('E', 'Проверяю'), ('K', 'Знаю')], default='S', max_length=1, verbose_name='Уровень знания')),
                ('word_count', models.CharField(choices=[('NC', 'Любое количество слов'), ('OW', 'Слово'), ('CB', 'Словосочетание'), ('PS', 'Часть предложения'), ('ST', 'Предложение')], default=['OW', 'CB'], max_length=2, verbose_name='Длина выражения')),
                ('date_start', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='NC', max_length=2, verbose_name='Добавлено после')),
                ('date_end', models.CharField(choices=[('DT', 'Сегодня'), ('D3', 'Три дня назад'), ('W1', 'Неделя назад'), ('W2', 'Две недели назад'), ('W3', 'Три недели назад'), ('W4', 'Четыре недели назад'), ('W7', 'Семь недель назад'), ('M3', 'Три месяца назад'), ('M6', 'Шесть месяцев назад'), ('M9', 'Девять месяцев назад'), ('NC', 'Добавлено')], default='DT', max_length=2, verbose_name='Добавлено до')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordcategory', verbose_name='Категория')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign.wordsource', verbose_name='Источник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки "Изучаем слова"',
                'verbose_name_plural': 'Настройки "Изучаем слова"',
            },
        ),
        migrations.DeleteModel(
            name='WordParams',
        ),
    ]
