# Generated by Django 4.2.14 on 2024-10-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0003_translateparams_delete_wordparams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translateparams',
            old_name='date_end',
            new_name='period_end_date',
        ),
        migrations.RenameField(
            model_name='translateparams',
            old_name='date_start',
            new_name='period_start_date',
        ),
        migrations.AlterField(
            model_name='translateparams',
            name='language_order',
            field=models.CharField(choices=[('RN', 'Перевод в случайном порядке'), ('TR', 'Перевод на русский язык'), ('FR', 'Перевод с русского язык')], default='TR', max_length=2, verbose_name='Порядок перевода'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
