# Generated by Django 4.2.14 on 2024-10-12 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0004_rename_date_end_translateparams_period_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateparams',
            name='word_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=['OW', 'CB'], size=None, verbose_name='Длина выражения'),
        ),
    ]
