# Generated by Django 4.2.14 on 2024-10-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0004_alter_translateparams_count_first_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='wordsource',
            options={'ordering': ('name',), 'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.RemoveField(
            model_name='wordcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='wordcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wordcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wordcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
