# Generated by Django 4.2.14 on 2024-10-19 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0005_alter_translateparams_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_word', to=settings.AUTH_USER_MODEL, verbose_name='Наставник, который добавил слово.'),
        ),
    ]
