# Generated by Django 4.2.14 on 2024-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0005_alter_wordcategory_options_alter_wordsource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wordsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
