# Generated by Django 4.2.14 on 2024-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0006_alter_wordsource_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_count',
            field=models.CharField(choices=[('NC', 'Любое'), ('OW', 'Слово'), ('CB', 'Словосочетание'), ('PS', 'Часть предложения'), ('ST', 'Предложение')], default='NC', max_length=2, verbose_name='Количество слов'),
        ),
    ]
