# Generated by Django 4.2.14 on 2024-11-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0007_alter_word_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateparams',
            name='count_first',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translateparams',
            name='count_last',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
