# Generated by Django 4.2.14 on 2024-11-07 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0009_alter_translateparams_period_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateparams',
            name='word_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('OW', 'Слово'), ('CB', 'Словосочетание'), ('PS', 'Часть предложения'), ('ST', 'Предложение')], max_length=16), default=['OW', 'CB'], size=None, verbose_name='Длина выражения'),
        ),
    ]
