# Generated by Django 4.2.14 on 2024-11-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0010_alter_translateparams_word_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translateparams',
            old_name='language_order',
            new_name='order',
        ),
    ]
