# Generated by Django 4.2.14 on 2024-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0011_rename_language_order_translateparams_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateparams',
            name='order',
            field=models.CharField(choices=[('RN', 'Случайный порядок'), ('TN', 'На родной'), ('FN', 'С родного')], default='TN', max_length=2, verbose_name='Порядок перевода'),
        ),
    ]
