# Generated by Django 4.2.14 on 2024-12-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0012_alter_translateparams_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateparams',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='translateparams',
            name='count_first',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='translateparams',
            name='count_last',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
