# Generated by Django 4.2.14 on 2025-01-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0014_translateparams_is_last_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translateparams',
            name='word_count',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_count',
        ),
    ]
