# Generated by Django 4.2.14 on 2025-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0015_remove_translateparams_word_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateparams',
            name='has_timeout',
            field=models.BooleanField(default=True),
        ),
    ]
