# Generated by Django 4.2.14 on 2025-01-23 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0018_remove_word_mentor_alter_word_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='assignedword',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignedword',
            name='word',
        ),
        migrations.AddField(
            model_name='assignedword',
            name='student',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_student', to=settings.AUTH_USER_MODEL, verbose_name='Назначено слово студенту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedword',
            name='word',
            field=models.ManyToManyField(blank=True, related_name='assigned_word', to='foreign.word', verbose_name='Назначенное слово'),
        ),
    ]
