# Generated by Django 5.2.4 on 2025-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя приложения')),
                ('schema_name', models.CharField(max_length=50, verbose_name='Имя схемы в БД')),
            ],
            options={
                'verbose_name': 'Основное приложение',
                'db_table': 'main"."app',
            },
        ),
    ]
