# Generated by Django 5.2.4 on 2025-07-28 05:54

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps

def create_schema(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor
) -> None:
    schema_editor.execute("""
        -- Schema for main app tables
        -- Contains base tables to inherit
        CREATE SCHEMA main;
        GRANT ALL PRIVILEGES ON SCHEMA main TO sv;
        ALTER SCHEMA main OWNER TO sv;
    """)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_schema),
    ]
