# Generated by Django 5.2.4 on 2025-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('schema_name', models.CharField(help_text='Каждое приложение расположено в отдельной схеме Postgres', max_length=50, verbose_name='Схема в БД')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'db_table': 'main"."app',
            },
        ),
    ]
