# Generated by Django 5.2.4 on 2025-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='app',
            name='schema_name',
            field=models.CharField(help_text='Каждое приложение расположено в отдельной схеме Postgres', max_length=50, verbose_name='Схема в БД'),
        ),
    ]
