# Generated by Django 6.0.1 on 2026-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование упражнения')),
                ('min_operand', models.SmallIntegerField(verbose_name='Минимальное значение операнда')),
                ('max_operand', models.SmallIntegerField(verbose_name='Максимальное значение операнда')),
                ('operation_type', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычисление'), ('mul', 'Умножение'), ('div', 'Деление')], default='add', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Условие упражнения вычисления',
                'verbose_name_plural': 'Условия упражнения вычисления',
                'db_table': 'math_exercise_condition',
            },
        ),
        migrations.CreateModel(
            name='MathAssignedConditionRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Условие назначенного матем. задания',
                'verbose_name_plural': 'Условия назначенного матем. задания',
                'db_table': 'math_exercise_assigned_condition_rel',
            },
        ),
        migrations.CreateModel(
            name='StudentCalculationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Назначенное условие вычисления',
                'verbose_name_plural': 'Назначенные условия вычисления',
                'db_table': 'math_exercise_condition_student',
            },
        ),
    ]
