"""Migration to create Exercise table with PostgreSQL table inheritance.

Creates:
1. Table `math.exercise` that inherits from `main.exercise`
2. Automatic ID generation using PostgreSQL identity column

Important notes:
- Inherits all columns from parent table `main.exercise`
- Child table can add additional columns specific to math exercises
- CASCADE used in reverse migration to ensure proper cleanup
"""

from django.db import migrations

# SQL for creating the inherited table
CREATE_TABLE_SQL = """
CREATE TABLE math.exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (main.exercise);
"""

# SQL for reverse migration
DROP_TABLE_SQL = """
DROP TABLE IF EXISTS math.exercise CASCADE;
"""


class Migration(migrations.Migration):
    """Migration to create math exercise table with inheritance."""

    dependencies = [
        ('contenttypes', '0001_initial'),  # Required for Django's content types
        ('main', '0001_create_base_exercise'),  # Parent table must exist
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLE_SQL,
            reverse_sql=DROP_TABLE_SQL,
        ),
    ]