# Generated by Django 5.2.4 on 2025-07-20 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FractionTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'math_fraction_task',
            },
        ),
        migrations.CreateModel(
            name='MathExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'math_exercise',
            },
        ),
        migrations.CreateModel(
            name='CalculationTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math.mathexercise')),
            ],
            options={
                'db_table': 'math_calculation_task',
            },
        ),
    ]
