# Generated by Django 6.0.1 on 2026-02-25 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('math', '0001_initial'),
        ('study', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathassignedconditionrel',
            name='assignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='math_condition_rel', to='study.exerciseassigned', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='mathassignedconditionrel',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_assigned_conditions', to='math.calculationcondition', verbose_name='Условие матем. задания'),
        ),
        migrations.AddField(
            model_name='studentcalculationcondition',
            name='calculation_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math.calculationcondition', verbose_name='Условия вычисления'),
        ),
        migrations.AddField(
            model_name='studentcalculationcondition',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorship', verbose_name='Наставничество'),
        ),
        migrations.AddConstraint(
            model_name='calculationcondition',
            constraint=models.CheckConstraint(condition=models.Q(('max_operand__gt', models.F('min_operand'))), name='max_gt_min'),
        ),
    ]
