# Generated by Django 5.2.7 on 2025-12-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('math', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathassignedconditionrel',
            name='assignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='math_condition_rel', to='study.exerciseassigned', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='mathassignedconditionrel',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_assigned_conditions', to='math.exercisecondition', verbose_name='Условие матем. задания'),
        ),
        migrations.AddField(
            model_name='mathexercise',
            name='discipline',
            field=models.ForeignKey(help_text='Exercise in discipline', on_delete=django.db.models.deletion.CASCADE, to='core.discipline', verbose_name='Дисциплина'),
        ),
    ]
