# Generated by Django 6.0.1 on 2026-02-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MathExercise',
        ),
    ]
