# Generated by Django 6.0.1 on 2026-02-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCalculationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('calculation_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math.calculationcondition', verbose_name='Calculation condition')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorship', verbose_name='Наставничество')),
            ],
            options={
                'verbose_name': 'Assigned calculation exercise condition',
                'verbose_name_plural': 'Assigned calculation exercise conditions',
                'db_table': 'math_exercise_condition_assigned',
            },
        ),
    ]
