# Generated by Django 5.2.4 on 2025-07-30 13:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('math', '0002_create_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand_1', models.DecimalField(decimal_places=3, editable=False, max_digits=3)),
                ('operand_2', models.DecimalField(decimal_places=3, editable=False, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'math"."calculation_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MathExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'db_table': 'math"."exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MathTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Значение должно быть > 0')], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('payment', 'Payment')], max_length=30, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'math"."transaction',
                'managed': False,
            },
        ),
    ]
