# Generated by Django 6.0.1 on 2026-02-21 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedCalculationCondition',
            new_name='StudentCalculationCondition',
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь добавивший упражнение'),
        ),
        migrations.AlterModelTable(
            name='studentcalculationcondition',
            table='math_exercise_condition_student',
        ),
    ]
