# Generated by Django 6.0.1 on 2026-05-16 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationcondition',
            options={'verbose_name': 'Calculation exercise condition', 'verbose_name_plural': 'Calculation exercise conditions'},
        ),
        migrations.AlterModelOptions(
            name='studentcalculationcondition',
            options={'verbose_name': 'Assigned calculation exercise condition', 'verbose_name_plural': 'Assigned calculation exercise conditions'},
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='max_operand',
            field=models.SmallIntegerField(verbose_name='Max operand value'),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='min_operand',
            field=models.SmallIntegerField(verbose_name='Min operand value'),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='operation_type',
            field=models.CharField(choices=[('add', 'Adding'), ('sub', 'Submission'), ('mul', 'Multiplication'), ('div', 'Division')], default='add', max_length=10),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated_at'),
        ),
        migrations.AlterField(
            model_name='calculationcondition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The user who created the exercise'),
        ),
        migrations.AlterField(
            model_name='studentcalculationcondition',
            name='calculation_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math.calculationcondition', verbose_name='Calculation condition'),
        ),
        migrations.AlterField(
            model_name='studentcalculationcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='studentcalculationcondition',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorship', verbose_name='Mentorship'),
        ),
        migrations.AlterField(
            model_name='studentcalculationcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
