# Generated by Django 6.0.1 on 2026-03-13 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationcondition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование упражнения'),
        ),
        migrations.AlterUniqueTogether(
            name='calculationcondition',
            unique_together={('name', 'user')},
        ),
    ]
