/**
 * Simple logger for Django applications
 *
 * Features:
 * - All logs (log, debug, info, warn) are shown ONLY on localhost/127.0.0.1
 * - Errors (error) are shown ALWAYS (even in production)
 * - Supports all standard console methods
 * - Includes timestamp in all logs
 *
 * Usage:
 * appLogger.log('Message')           // Only on localhost
 * appLogger.error('Error')           // Always visible
 * appLogger.warn('Warning')          // Only on localhost
 * appLogger.info('Information')      // Only on localhost
 * appLogger.debug('Debug message')   // Only on localhost
 *
 * For production: no changes needed, logs are automatically hidden
 *
 * ⚡ HOW TO ENABLE LOGS IN PRODUCTION:
 * 1. In browser console, run:
 *    appLogger.enable(true)           // Enable all logs
 *    appLogger.enable(false)          // Disable logs (default)
 *
 * 2. OR persist across page reloads:
 *    localStorage.setItem('debug_logs', 'true')   // Enable
 *    localStorage.setItem('debug_logs', 'false')  // Disable
 *    location.reload()                            // Reload page
 *
 * 3. Quick one-liner for production debugging:
 *    // Paste in browser console:
 *    localStorage.debug_logs='true';location.reload()
 *
 * Generated by: DeepSeek AI Assistant
 * Version: 1.1.0 (added timestamps)
 * Created: 2025.12.16
 * Updated: 2025.12.16
 */

const isLocal =
  window.location.hostname.includes("localhost") ||
  window.location.hostname.includes("127.0.0.1");

// Helper function to format timestamp
const getTimestamp = () => {
  const now = new Date();
  return now.toLocaleTimeString("en-US", {
    hour12: false,
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    fractionalSecondDigits: 3,
  });
};

window.appLogger = {
  /**
   * Main log (console.log equivalent)
   * Shown only on localhost/127.0.0.1
   * Includes timestamp
   */
  log: (...args) =>
    (window._forceLogs || isLocal) &&
    console.log(`[${getTimestamp()}]`, "[LOG]", ...args),

  /**
   * Debug log (console.debug equivalent)
   * Shown only on localhost/127.0.0.1
   * Includes timestamp
   */
  debug: (...args) =>
    (window._forceLogs || isLocal) &&
    console.debug(`[${getTimestamp()}]`, "[DEBUG]", ...args),

  /**
   * Info messages (console.info equivalent)
   * Shown only on localhost/127.0.0.1
   * Includes timestamp
   */
  info: (...args) =>
    (window._forceLogs || isLocal) &&
    console.info(`[${getTimestamp()}]`, "[INFO]", ...args),

  /**
   * Warnings (console.warn equivalent)
   * Shown only on localhost/127.0.0.1
   * Includes timestamp
   */
  warn: (...args) =>
    (window._forceLogs || isLocal) &&
    console.warn(`[${getTimestamp()}]`, "[WARN]", ...args),

  /**
   * Critical errors (console.error equivalent)
   * Shown ALWAYS, even in production
   * Includes timestamp
   */
  error: (...args) => console.error(`[${getTimestamp()}]`, "[ERROR]", ...args),

  /**
   * Log grouping (only on localhost)
   */
  group: (...args) =>
    (window._forceLogs || isLocal) &&
    console.group(`[${getTimestamp()}]`, ...args),
  groupEnd: () => (window._forceLogs || isLocal) && console.groupEnd(),
  groupCollapsed: (...args) =>
    (window._forceLogs || isLocal) &&
    console.groupCollapsed(`[${getTimestamp()}]`, ...args),

  /**
   * Check current environment
   * @returns {boolean} true if running locally
   */
  isLocal: () => isLocal,

  /**
   * Force enable/disable logs (for production debugging)
   */
  enable: (force = null) => {
    if (force !== null) {
      window._forceLogs = force;
      console.log(
        `[${getTimestamp()}] 🔍 Logging ${force ? "ENABLED" : "DISABLED"}`,
      );
    }
    return window._forceLogs || isLocal;
  },

  /**
   * Get current logging status
   * @returns {string} 'local', 'production', or 'forced'
   */
  status: () => {
    if (window._forceLogs) return "forced";
    if (isLocal) return "local";
    return "production";
  },

  /**
   * Performance measurement helper
   * @param {string} label - Measurement label
   * @returns {Function} Function to call when operation ends
   */
  time: (label) => {
    const start = performance.now();
    return () => {
      const duration = performance.now() - start;
      if (window._forceLogs || isLocal) {
        console.log(
          `[${getTimestamp()}] ⏱️ ${label}: ${duration.toFixed(2)}ms`,
        );
      }
    };
  },
};

// Auto-enable if localStorage flag is set
if (localStorage.getItem("debug_logs") === "true") {
  window._forceLogs = true;
  console.log(`[${getTimestamp()}] 🔍 Forced logging enabled via localStorage`);
}
