/**
 * Simple logger for Django applications
 * 
 * Features:
 * - All logs (log, debug, info, warn) are shown ONLY on localhost/127.0.0.1
 * - Errors (error) are shown ALWAYS (even in production)
 * - Supports all standard console methods
 * 
 * Usage:
 * appLogger.log('Message')           // Only on localhost
 * appLogger.error('Error')           // Always visible
 * appLogger.warn('Warning')          // Only on localhost
 * appLogger.info('Information')      // Only on localhost
 * appLogger.debug('Debug message')   // Only on localhost
 * 
 * For production: no changes needed, logs are automatically hidden
 * 
 * ⚡ HOW TO ENABLE LOGS IN PRODUCTION:
 * 1. In browser console, run:
 *    appLogger.enable(true)           // Enable all logs
 *    appLogger.enable(false)          // Disable logs (default)
 * 
 * 2. OR persist across page reloads:
 *    localStorage.setItem('debug_logs', 'true')   // Enable
 *    localStorage.setItem('debug_logs', 'false')  // Disable
 *    location.reload()                            // Reload page
 * 
 * 3. Quick one-liner for production debugging:
 *    // Paste in browser console:
 *    localStorage.debug_logs='true';location.reload()
 * 
 * Generated by: DeepSeek AI Assistant
 * Version: 1.0.0
 * Created: 2025.12.16
 */

const isLocal = window.location.hostname.includes('localhost') 
                || window.location.hostname.includes('127.0.0.1');

window.appLogger = {
    /**
     * Main log (console.log equivalent)
     * Shown only on localhost/127.0.0.1
     */
    log: (...args) => (window._forceLogs || isLocal) && console.log('[LOG]', ...args),
    
    /**
     * Debug log (console.debug equivalent)
     * Shown only on localhost/127.0.0.1
     */
    debug: (...args) => (window._forceLogs || isLocal) && console.debug('[DEBUG]', ...args),
    
    /**
     * Info messages (console.info equivalent)
     * Shown only on localhost/127.0.0.1
     */
    info: (...args) => (window._forceLogs || isLocal) && console.info('[INFO]', ...args),
    
    /**
     * Warnings (console.warn equivalent)
     * Shown only on localhost/127.0.0.1
     */
    warn: (...args) => (window._forceLogs || isLocal) && console.warn('[WARN]', ...args),
    
    /**
     * Critical errors (console.error equivalent)
     * Shown ALWAYS, even in production
     */
    error: (...args) => console.error('[ERROR]', ...args),
    
    /**
     * Log grouping (only on localhost)
     */
    group: (...args) => (window._forceLogs || isLocal) && console.group(...args),
    groupEnd: () => (window._forceLogs || isLocal) && console.groupEnd(),
    groupCollapsed: (...args) => (window._forceLogs || isLocal) && console.groupCollapsed(...args),
    
    /**
     * Check current environment
     * @returns {boolean} true if running locally
     */
    isLocal: () => isLocal,
    
    /**
     * Force enable/disable logs (for production debugging)
     * @param {boolean|null} force - true to enable, false to disable, null to get current state
     * @returns {boolean} current logging state
     * 
     * Example for production:
     * // In browser console:
     * appLogger.enable(true)  // Enable logs
     * appLogger.log('Now visible!')
     * appLogger.enable(false) // Disable logs
     */
    enable: (force = null) => {
        if (force !== null) {
            window._forceLogs = force;
            console.log(`🔍 Logging ${force ? 'ENABLED' : 'DISABLED'}`);
        }
        return window._forceLogs || isLocal;
    },
    
    /**
     * Get current logging status
     * @returns {string} 'local', 'production', or 'forced'
     */
    status: () => {
        if (window._forceLogs) return 'forced';
        if (isLocal) return 'local';
        return 'production';
    }
};

// Auto-enable if localStorage flag is set
if (localStorage.getItem('debug_logs') === 'true') {
    window._forceLogs = true;
    console.log('🔍 Forced logging enabled via localStorage');
}