name: Django tests
run-name: Django tests

on:
  push:
    branches: [ 'main', 'development' ]
    paths-ignore: [
      '**.md', '**.rst', '**/.env.**', '**/.gitignore', '**/.dockerignore',
      '**/Makefile', '**/**.lock', '**/**.toml', '**/**.yml',
      'app-wse/docs/**', 'nginx/**'
    ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set environment variables
        working-directory: app-wse
        run: |
          mv .env.example           .env
          mv .env.postgres.example  .env.postgres

      - name: Up Docker
        run: |
          make up
          sleep 5s
          make migrate
          make collectstatic

      - name: Run tests
        run: make test