name: Playwright
run-name: Playwright test

on:
  push:
    branches: [ 'main', 'development' ]
    paths-ignore: [
      '**.md', '**/.env.**', '**/.gitignore', '**/.dockerignore',
      '**/Makefile', '**/**.lock', '**/**.toml', '**/**.yml',
      'app-wse/docs/**', 'nginx/**'
    ]
  workflow_dispatch:

jobs:
  testing-app-changes-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wselfedu app
        uses: actions/checkout@v4

      - name: Start wselfedu app
        run: |
          cp app-wse/.env.example           app-wse/.env
          cp app-wse/.env.postgres.example  app-wse/.env.postgres
          docker compose up -d
          sleep 5s
          make migrate
          make collectstatic

      - name: Load fixture
        run: >
          docker compose exec app-wse python manage.py
          loaddata tests/fixtures/wse-db-fixture-users.json

      - name: Checkout third party repo testing app
        uses: actions/checkout@v4
        with:
          repository: svmikurov/wselfedu-plw
          path: ./tests

      - name: Start testing app
        working-directory: ./tests
        run: |
          mv .env.example .env
          docker build -t plw-test .

      - name: Run web app tests by a Playwright
        working-directory: ./tests
        run: |
          docker run --network=host plw-test
