name: Playwright
run-name: Playwright

on:
  push:
    branches: [ 'main', 'development' ]
    paths-ignore: [
      '**.md', '**.rst', '.env.**', '**.lock', '**.toml', '**/**.yml',
      '.gitignore', '**/**.dockerignore', 'Makefile', 'nginx.conf',
      'setup.cfg', 'docs/**',
    ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          mv .env_vars/.env.example           .env_vars/.env
          mv .env_vars/.env.wse.example       .env_vars/.env.wse
          mv .env_vars/.env.postgres.example  .env_vars/.env.postgres

      - name: Up Docker
        run: |
          make up
          sleep 5s
          make migrate
          make collectstatic

      - name: Run tests
        run: make plw

      # sometimes tests fail when the page doesn't load
      - name: Re-run failed tests
        run: make plw-lf
