-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-23
-- Description: Creating project tables via PostgreSQL

-- Starting a transaction
BEGIN;

-- Create Base exercise table
CREATE TABLE base_exercise (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create Math app exercise (inherits)
CREATE TABLE math_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base_exercise);

-- Create Lang app exercise (inherits)
CREATE TABLE lang_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base_exercise);


-- Создаем функцию триггера
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Создаем триггер
CREATE TRIGGER base_exercise
BEFORE UPDATE ON math_exercise
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Applying Changes
COMMIT;