-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-23
-- Description: Creating project tables via PostgreSQL


-- Create Base exercise table
CREATE TABLE base_exercise (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(30)
);


-- Create Math app exercise (inherits)
CREATE TABLE math_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
) INHERITS (base_exercise);


-- Create Lang app exercise (inherits)
CREATE TABLE lang_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
) INHERITS (base_exercise);