-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-25
-- Description: Contains Lang app schemas

-- Starting a transaction
BEGIN;

-- Create Lang app exercise (inherits)
CREATE TABLE lang.exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base.exercise);

-- Applying Changes
COMMIT;