-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-23
-- Description: Contains table schemas

-- Starting a transaction
BEGIN;

-- Create Base exercise table
CREATE TABLE base_exercise (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create Math app exercise (inherits)
CREATE TABLE math_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base_exercise);

-- Create Lang app exercise (inherits)
CREATE TABLE lang_exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base_exercise);

-- Applying Changes
COMMIT;