-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-25
-- Description: Contains Math app schemas

-- Starting a transaction
BEGIN;

-- Create Math app exercise (inherits)
CREATE TABLE math.exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base.exercise);

-- Applying Changes
COMMIT;