-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-25
-- Description: Defines Users app schemas

BEGIN;

CREATE TABLE users.balance (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL UNIQUE,
    total DECIMAL(11, 2),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users.customuser(id)
        ON DELETE CASCADE
);

COMMIT;