-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-25
-- Description: Defines Math app schemas

BEGIN;

-- Create Math app exercise (inherits)
CREATE TABLE math.exercise (
    id INT GENERATED BY DEFAULT AS IDENTITY
) INHERITS (base.exercise);

-- Math app reward bonus transaction table
CREATE TABLE math.transaction (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT fr_user
        FOREIGN KEY (user_id)
        REFERENCES users.customuser(id)
        ON DELETE CASCADE
) INHERITS (base.transaction);

COMMIT;