-- Version: 0.1.0
-- Autor: Sergei Mikurov
-- Date: 2025-07-25
-- Updated: 2025-07-26
-- Description: Defines Math app schemas

BEGIN;

-- Math app reward bonus transaction table
CREATE TABLE math.transaction (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT fr_user
        FOREIGN KEY (user_id)
        REFERENCES users.customuser(id)
        ON DELETE CASCADE
) INHERITS (main.transaction);

COMMIT;